### ISSUE TITLE
semver version updating

### ISSUE THREAD

**Issue by hellvinz** [tambien/StartAudioContext#1]
Hi,
first of all thanks for this package.
Just wanted to report that you haven't followed semantic versioning when you have changed the API from 1.1.0 to 1.2.0. Since you have removed methods from the previous API, you should have make it a 2.0.0.
This could have impacted people like us who have set a version of "^1.1.0" in their package.json.
Again no big deal, just wanted to warn you for the next time
cheers

**Comment by tambien** [comment]
oops! I'll pay more attention to this to try avoid introducing any bugs in people's code. thanks for the note.
